export const garmentSpecificMeasurements = {
  kaftan: [
    "Neck",
    "Shoulder",
    "Chest",
    "NaturalWaist",
    "KaftanLength",
    "TrouserLength",
    "TrouserWaist",
    "Hip",
    "Thigh",
    "Knee",
    "Ankle",
    "SleeveLength",
    "SleeveWidth",
  ],
  agbada: [
    "Neck",
    "Shoulder",
    "Chest",
    "NaturalWaist",
    "KaftanLength",
    "AgbadaLength",
    "TrouserLength",
    "TrouserWaist",
    "Hip",
    "Thigh",
    "Knee",
    "Ankle",
    "SleeveLength",
    "SleeveWidth",
  ],
  shortSleeveShirt: [
    "Neck",
    "Shoulder",
    "Chest",
    "NaturalWaist",
    "ShirtLength",
    "SleeveLength",
    "SleeveWidth",
  ],
  longSleeveShirt: [
    "Neck",
    "Shoulder",
    "Chest",
    "NaturalWaist",
    "ShirtLength",
    "SleeveLength",
    "SleeveWidth",
    "Bicep",
    "Wrist",
  ],
  suit: [],
};
