export const garmentSpecificMeasurements = {
  kaftan: [
    "Neck",
    "Shoulder",
    "Chest",
    "NaturalWaist",
    "KaftanLength",
    "TrouserLength",
    "TrouserWaist",
    "Hip",
    "ThighWidth",
    "KneeWidth",
    "AnkleWidth",
    "ShortSleeve",
    "LongSleeve",
    "ShortSleeveWidth",
    "Bicep",
  ],
  agbada: [
    "Neck",
    "Shoulder",
    "Chest",
    "NaturalWaist",
    "KaftanLength",
    "AgbadaLength",
    "TrouserLength",
    "TrouserWaist",
    "Hip",
    "ThighWidth",
    "KneeWidth",
    "AnkleWidth",
    "LongSleeve",
    "ShortSleeve",
    "ShortSleeveWidth",
    "Bicep",
  ],

  shirt: [
    "Neck",
    "Shoulder",
    "Chest",
    "NaturalWaist",
    "ShirtLength",
    "LongSleeve",
    "ShortSleeve",
    "ShortSleeveWidth",
    "Bicep",
  ],
  suit: [
    "Neck",
    "Shoulder",
    "SuitChest",
    "SuitWaist",
    "SuitLength",
    "TrouserLength",
    "TrouserWaist",
    "Hip",
    "Thigh",
    "Knee",
    "Ankle",
    "SleeveLength",
    "SleeveWidth",
  ],
  trouser: ["TrouserLength", "TrouserWaist", "Hip", "Thigh", "Knee", "Ankle"],
};
